-- DROP EVERYTHING
DROP TABLE addresses CASCADE;
DROP TABLE emails CASCADE;
DROP TABLE phone_numbers CASCADE;
DROP TABLE people CASCADE;
DROP TABLE emails_link CASCADE;
DROP TABLE phone_link CASCADE;
